FROM python:3.12-slim

WORKDIR /app
RUN apt-get update && apt-get install -y python3-pip && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir fastapi uvicorn jinja2 onnx pillow numpy requests python-multipart
RUN pip3 install --no-cache-dir onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
RUN pip3 install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cu124


COPY model_splitter ./model_splitter
COPY common ./model_splitter/common

WORKDIR /app/model_splitter
EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
